### PR TITLE
Docs build fixes

### PR DESCRIPTION
**Pull request by lkubb**
Fixes: https://github.com/saltstack/salt-extension/issues/44

Based on https://github.com/saltstack/salt-extension/pull/42 because there are no requirement files to fix in this repo before merging it

### CODE REVIEW

**Review by s0undt3ch — APPROVED** [review]
Is this still a valid and wanted PR?

**Comment by lkubb** [comment]
The underlying issue is still valid, without this the docs are pretty broken afair. If this tool is still intended to be the official way to create an extension, I think it should be fixed.

In the copier template, I included some additional changes built on top of this PR:

* virtualnames as module doc headings, except for `utils` (import path here ofc)
* include nested `utils` modules
* removed `docs/all.rst` nesting by rendering the module index directly in `docs/index.rst`

I'm happy to contribute those in a separate PR if desired.

**Comment by s0undt3ch** [comment]
If the copier template is better and more maintainable than this code, I'm in favor of advising users to use that instead.

**Comment by lkubb** [comment]
I do think it's a bit more maintainable and easier to add new functionality to, in addition to allowing boilerplate updates for existing projects. We should probably transfer it into the `salt-extensions` org if it becomes an official recommendation though.

**Review by twangboy — APPROVED** [review]

**Pull request merged**
